[package]
name = "blaster_boss_2000"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
rand = "0.8.5"
rand_distr = "0.4.3"

## Storing networks
bincode = "1.3.3"
serde = "1.0.210"
serde_derive = "1.0.210"
rayon = "1.10.0"
